# Generated by Django 5.0.3 on 2024-03-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_carro_delete_inventario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carro',
            new_name='Año2024',
        ),
    ]
