# Generated by Django 5.0.3 on 2024-03-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_marca_año2024_barrio_rename_pais_año2024_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=120)),
                ('cantidad', models.IntegerField()),
                ('pais', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Año2024',
        ),
    ]
