# Generated by Django 5.0.3 on 2024-03-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_carro_delete_año2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carro',
            new_name='Año2024',
        ),
    ]
