# Generated by Django 5.0.3 on 2024-03-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_rename_carro_año2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='año2024',
            old_name='marca',
            new_name='barrio',
        ),
        migrations.RenameField(
            model_name='año2024',
            old_name='pais',
            new_name='mes',
        ),
    ]
