# Generated by Django 5.0.3 on 2024-03-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_rename_marca_año2024_barrio_rename_pais_año2024_mes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Año2024',
            new_name='Barrio1',
        ),
    ]
