# Generated by Django 5.0.3 on 2024-03-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_rename_año2024_barrio1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Barrio1',
            new_name='Año2024',
        ),
    ]
