# Generated by Django 5.0.3 on 2024-03-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_año2015_año2016_año2017_año2018_año2019_año2020_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='año2023',
            old_name='barrio',
            new_name='barrio2',
        ),
        migrations.RenameField(
            model_name='año2023',
            old_name='cantidad',
            new_name='cantidad2',
        ),
        migrations.RenameField(
            model_name='año2023',
            old_name='mes',
            new_name='mes2',
        ),
    ]
