# Generated by Django 5.0.3 on 2024-03-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_rename_barrio_año2023_barrio2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Año2015',
        ),
        migrations.DeleteModel(
            name='Año2016',
        ),
        migrations.DeleteModel(
            name='Año2017',
        ),
        migrations.DeleteModel(
            name='Año2018',
        ),
        migrations.DeleteModel(
            name='Año2019',
        ),
    ]
