# Generated by Django 5.0.3 on 2024-03-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_delete_año2015_delete_año2016_delete_año2017_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='año2020',
            old_name='barrio',
            new_name='barrio5',
        ),
        migrations.RenameField(
            model_name='año2020',
            old_name='cantidad',
            new_name='cantidad5',
        ),
        migrations.RenameField(
            model_name='año2020',
            old_name='mes',
            new_name='mes5',
        ),
        migrations.RenameField(
            model_name='año2021',
            old_name='barrio',
            new_name='barrio4',
        ),
        migrations.RenameField(
            model_name='año2021',
            old_name='cantidad',
            new_name='cantidad4',
        ),
        migrations.RenameField(
            model_name='año2021',
            old_name='mes',
            new_name='mes4',
        ),
        migrations.RenameField(
            model_name='año2022',
            old_name='barrio',
            new_name='barrio3',
        ),
        migrations.RenameField(
            model_name='año2022',
            old_name='cantidad',
            new_name='cantidad3',
        ),
        migrations.RenameField(
            model_name='año2022',
            old_name='mes',
            new_name='mes3',
        ),
    ]
